name: Build Woo Payment Reminder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual execution
  release:
    types: [published] # Runs when a new release is published

jobs:
  build:
    name: Package Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP Archive
        run: |
          zip -r woo-payment-reminder.zip . -x "*.git*" ".github/*" "ci/*"

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: woo-payment-reminder
          path: woo-payment-reminder.zip
          retention-days: 7 # Artifacts will be available for 7 days

  release:
    name: Publish Release ZIP
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download ZIP Artifact
        uses: actions/download-artifact@v4
        with:
          name: woo-payment-reminder
          path: .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: woo-payment-reminder.zip
